-- 五险一金计算器数据库创建脚本（简化版）
-- 请在 Supabase SQL 编辑器中执行以下命令

-- 删除现有表（如果存在）
DROP TABLE IF EXISTS results;
DROP TABLE IF EXISTS salaries;
DROP TABLE IF EXISTS cities;

-- 创建 cities 表（城市标准表）
CREATE TABLE cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_name TEXT NOT NULL,
  year TEXT NOT NULL,
  base_min BIGINT NOT NULL,        -- 社保基数下限
  base_max BIGINT NOT NULL,        -- 社保基数上限
  rate FLOAT NOT NULL,           -- 综合缴纳比例 (如 0.15),
  UNIQUE(city_name, year)          -- 添加唯一约束，避免重复数据
);

-- 创建 salaries 表（员工工资表）
CREATE TABLE salaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL,
  employee_name TEXT NOT NULL,
  month TEXT NOT NULL,          -- 年份月份 (YYYYMM)
  salary_amount BIGINT NOT NULL,    -- 该月工资金额
  -- 添加唯一约束，避免重复插入
  UNIQUE(employee_id, month)
);

-- 创建 results 表（计算结果表）
CREATE TABLE results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name TEXT NOT NULL,
  year TEXT NOT NULL,               -- 计算年份
  avg_salary FLOAT NOT NULL,        -- 年度月平均工资
  contribution_base FLOAT NOT NULL, -- 最终缴费基数
  company_fee FLOAT NOT NULL,       -- 公司缴纳金额
  -- 添加唯一约束，避免重复计算
  UNIQUE(employee_name, year)
);

-- 或者完全禁用 RLS（如果不需要行级安全）
ALTER TABLE cities DISABLE ROW LEVEL SECURITY;
ALTER TABLE salaries DISABLE ROW LEVEL SECURITY;
ALTER TABLE results DISABLE ROW LEVEL SECURITY;